print("************************")
print("Welcome to Contact Book")
print("************************")
print("What do you want to do?")
print("1. Add a contact")
print("2. list contacts")
print("3. Delete a contact")
print("4. Update a contact")   
print("5. Search a contact")
print("6. Exit")